name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: TIDFGK-PDF
        path: tidfgk/tidfgk.pdf
        if-no-files-found: error
